generate Api for my backend
osbentech/two-apps-setup pull request #1
Opened 2023-04-07 21:36 UTC by osbentech

- Create a new Rails API app called 'hello-rails-back-end'.
    - Initialize your project with Git.
    -  Make sure that your project has a Postgres database set up.
    - Create a table for storing your messages and create 5 different greetings.
    - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

    - Create a new React app called 'hello-react-front-end'
    - Initialize your project with Git.
    - Create the App component with react-router.
    - Create the Greeting component that will display a greeting. Set it up as a route in your App component.
    - Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
    - Display the random greeting in your Greeting component.

2023-04-07 21:43 UTC, MahmoudBakr23 commented
### Hi @osbentech 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

**Invalid Submission**
- Please attach the link to the front-end repo in the README file and this PR summary, and do the other way around in the front-end's repo README file and PR as well. 🙏 
-

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

2023-04-20 12:32 UTC, Gambit142 requested changes
Hi @osbentech 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- For the frontend project, you ought to create a pull request from a `feature` branch to the `dev` branch. Currently, all your changes are being made on the `dev` branch. Kindly correct this 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-20 13:56 UTC, franclobo requested changes
Hi @osbentech, 

# Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/233388843-751d408c-6002-40db-bb10-e2810d1eff14.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct db ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 13:56 UTC, franclobo commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- **[OPTIONAL]** I recommend loading the data base using db:seed to have greetings to show 👇🏽 

```ruby
Message.create!(message: "Hello")
Message.create!(message: "Hi!")
Message.create!(message: "Hola")
Message.create!(message: "Bonjour")
Message.create!(message: "Ciao") 
```

2023-04-20 13:56 UTC, franclobo commented on config/routes.rb
> +end
- [ ] Please add the root to the index page to load the greetings, not to the default page (Rails logo).

`root to: 'api/v1/roots#index'`

2023-04-20 15:01 UTC, prolajumokeoni commented
Hi @osbentech 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters setup, please add the linters config in your frontend repository 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-20 17:28 UTC, arslanbisharat commented
Hi @osbentech , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a PR without proper description. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-20 17:56 UTC, afanimartin approved these changes
Hi @osbentech,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Route for random messages added to the `routes.rb` file
- A controller for random messages and one action created
- Database migration for messages table exists

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 19:23 UTC, merged